In [1]:
import numpy as np

In [3]:
arr = np.arange(11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.sqrt(arr)  # 平方根の計算

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [7]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [8]:
A = np.random.randn(10)

In [9]:
A

array([ 0.65878335,  0.19526702, -0.34805142, -0.02779446,  0.3384986 ,
        1.15947732, -1.58894998,  1.00682843, -0.46097057, -2.63931692])

In [11]:
B = np.random.randn(10)

In [12]:
B

array([-0.39942619, -1.1649466 ,  0.96978518,  0.67263576, -0.06479967,
       -1.56402682,  0.27529937, -0.12480386,  0.35872778,  3.19644442])

In [13]:
np.add(A, B)

array([ 0.25935716, -0.96967958,  0.62173377,  0.64484131,  0.27369893,
       -0.4045495 , -1.31365061,  0.88202457, -0.10224279,  0.5571275 ])

In [14]:
np.maximum(A, B)

array([ 0.65878335,  0.19526702,  0.96978518,  0.67263576,  0.3384986 ,
        1.15947732,  0.27529937,  1.00682843,  0.35872778,  3.19644442])

In [15]:
np.minimum(A, B)

array([-0.39942619, -1.1649466 , -0.34805142, -0.02779446, -0.06479967,
       -1.56402682, -1.58894998, -0.12480386, -0.46097057, -2.63931692])